print("=== POR QUE SEMPRE PRECISAMOS GUARDAR A CHAVE ===\n")

# Exemplo: Vamos supor que temos uma hash table de tamanho 7
# E vamos inserir elementos que causam colisões

print("Scenario: Hash table tamanho 7")
print("Elementos a inserir: 12, 19, 26 (todos fazem hash para posição 5)")
print()

print("--- SEPARATE CHAINING ---")
print("Posição 5 ficaria assim:")
print("tabela[5] = [(12, 'João'), (19, 'Maria'), (26, 'Pedro')]")
print()
print("Quando buscar por 19:")
print("1. Calcula hash: 19 % 7 = 5")
print("2. Vai na posição 5 e encontra: [(12, 'João'), (19, 'Maria'), (26, 'Pedro')]")
print("3. Percorre a lista comparando CHAVES:")
print("   - 12 == 19? NÃO")
print("   - 19 == 19? SIM! → retorna 'Maria'")
print("4. SEM a chave armazenada, seria IMPOSSÍVEL saber qual elemento buscar!")
print()

print("--- OPEN ADDRESSING (Linear Probing) ---")
print("Tabela ficaria assim:")
print("tabela[5] = 12 ('João')")
print("tabela[6] = 19 ('Maria')")  
print("tabela[0] = 26 ('Pedro')")  # Wraparound
print()
print("Quando buscar por 19:")
print("1. Calcula hash: 19 % 7 = 5")
print("2. Verifica posição 5: encontra chave 12")
print("   - 12 == 19? NÃO → continua procurando")
print("3. Verifica posição 6: encontra chave 19") 
print("   - 19 == 19? SIM! → retorna 'Maria'")
print("4. SEM a chave armazenada, seria IMPOSSÍVEL distinguir elementos!")
print()

print("--- E SE NÃO GUARDÁSSEMOS A CHAVE? ---")
print("❌ SEPARATE CHAINING:")
print("   bucket = ['João', 'Maria', 'Pedro']")
print("   Como saber qual é qual? Impossível!")
print()
print("❌ OPEN ADDRESSING:")
print("   tabela[5] = 'João'")
print("   tabela[6] = 'Maria'")
print("   Se buscarmos por 19, como saber se 'Maria' é o valor de 19 ou de outra chave?")
print("   Seria impossível distinguir!")
print()

print("🎯 CONCLUSÃO:")
print("A CHAVE é fundamental em ambos os métodos porque:")
print("1. É a única forma de IDENTIFICAR qual elemento estamos buscando")
print("2. Permite DISTINGUIR entre elementos que colidiram")
print("3. É necessária para VERIFICAR se encontramos o elemento correto")
print()
print("Hash table = Estrutura para mapear CHAVES → VALORES")
print("Sem a chave, perdemos a capacidade de fazer esse mapeamento!")
